site_name: Facile Docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/favicon.ico
  
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      # primary: blue
      toggle:
        icon: material/brightness-auto
        name: Mudar para modo escuro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      # primary: blue
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Mudar para automático

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      # primary: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

nav:
  - Home: 'index.md'
  - Facile XML-e: 
    - Introdução: 'xmle/index.md'
    - Notas de Versão: 'xmle/release-notes.md'
    - Download do Patch: 'xmle/download-patch.md'
    - Dicionário de Dados: 'xmle/dicionario-dados.md'
    - Instalação:
      - Passo 01 - Aplicando o Patch: 'xmle/instalacao/aplicar-patch.md'
      - Passo 02 - Compatibilizador: 'xmle/instalacao/compatibilizador.md'
      - Passo 03 - Pontos de Entrada: 'xmle/instalacao/ponto-entrada-padrao.md'
      - Passo 04 - Criando os Menus: 'xmle/instalacao/menus.md'
      - Passo 05 - Configurar os Jobs: 'xmle/instalacao/configura-jobs.md'
    - Manuais:
      - 03 - Manual do Usuário: 'xmle/manuais/manual-usuario.md'
      - 09 - CheckDoc: 'xmle/manuais/checkdoc.md'
      - 14 - Configuração do Webservice Checkdoc: 'xmle/manuais/webservice.md'
  - CIFA:
    - Introdução: 'cifa/index.md'

plugins:
  - search
  
copyright: Copyright &copy; 2010 - 2022 Facile Sistemas

extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/facilesistemass
      name: Facile no Facebook

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/facilesistemas/
      name: Siga nosso instagram
    
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/facile-solu-es-em-sistemas/
      name: LinkedIN

